# Generated by Django 3.1.5 on 2021-03-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_module', '0002_auto_20210309_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_branch', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='login_module.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('assignment_title', models.CharField(max_length=50)),
                ('assignment_file', models.FileField(null=True, upload_to='assignments/')),
                ('added_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_course', to='teacher_module.course')),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_teacher', to='login_module.teacher')),
            ],
        ),
    ]
