# Generated by Django 3.1.5 on 2021-03-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
