# Generated by Django 3.1.5 on 2021-03-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_email', models.CharField(help_text='write your email', max_length=20, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_semester', models.IntegerField()),
                ('student_branch', models.CharField(max_length=50)),
                ('student_dob', models.DateTimeField()),
                ('student_address', models.CharField(help_text='write your address', max_length=100)),
                ('student_city', models.CharField(max_length=20)),
                ('student_state', models.CharField(max_length=20)),
                ('student_zip', models.CharField(max_length=6)),
                ('student_mobile_no', models.CharField(max_length=10)),
                ('student_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_email', models.CharField(help_text='write your email', max_length=20, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=20)),
                ('teacher_gender', models.CharField(max_length=10)),
                ('teacher_dob', models.DateTimeField()),
                ('teacher_address', models.CharField(help_text='write your address', max_length=100)),
                ('teacher_city', models.CharField(max_length=20)),
                ('teacher_state', models.CharField(max_length=20)),
                ('teacher_zip', models.CharField(max_length=6)),
                ('teacher_mobile_no', models.CharField(max_length=10)),
            ],
        ),
    ]
