# Generated by Django 3.1.5 on 2021-03-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_zip',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_zip',
        ),
    ]
