# Generated by Django 3.1.5 on 2021-03-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_module', '0002_auto_20210317_1713'),
        ('login_module', '0002_auto_20210309_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='teacher_module.course')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='login_module.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
