# Generated by Django 3.1.5 on 2021-03-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0002_auto_20210309_1723'),
        ('teacher_module', '0002_auto_20210317_1713'),
        ('student_module', '0002_submission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('student', 'assignment')},
        ),
    ]
