# Generated by Django 3.1.5 on 2021-03-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_module', '0004_auto_20210318_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_added_date',
            field=models.DateTimeField(default=None),
        ),
    ]
